RubyOnRilas_testdusoleil/config/routes.rb
Dusoleil::Application.routes.draw do
  #devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)
  # devise_for :admin_users, ActiveAdmin::Devise.config, ActiveAdmin::Devise.config
  devise_for :users

  root :to => "hits#create"

  resources :hits, :only => [:index] do
    post 'ban', :on => :member
    get 'ban', :on => :member
    get 'error_logs', :on => :collection
  end
   get 'check_hit/:id', to: "hits#check_hit"
  resources :campaigns, :except => :edit do
    get 'campaign_clone', :on => :member
    get 'stats', :on => :member
    get 'hits', :on => :member
    get 'hit_counts', :on => :member
    get 'autocomplete', :on => :collection
    get 'referer_autocomplete', :on => :collection
  end
  
  resources :hit_counts, :only => [:index,:put] do
    put 'block', :on => :member
  end

  resources :hit_stats, :only => [:index]
  
  resource :sysconfigs, :only => [:show, :update], :path => "system" do
    post 'unban_me',    :on => :collection
    post 'reset_cache', :on => :collection
    put  'sync_data',   :on => :collection

    get 'search_ip',      :on => :collection
    post 'add_ban_ip',    :on => :collection
    post 'delete_ban_ip', :on => :collection
    post 'upload_ip_list',:on => :collection 

    get 'search_agent',      :on => :collection
    post 'add_ban_agent',    :on => :collection
    post 'delete_ban_agent', :on => :collection
    post 'upload_agent_list',:on => :collection 
  end

  resources :trackers, :except => :edit
end

RubyOnRilas_testdusoleil/app/models/sysconfig.rb
class Sysconfig < ActiveRecord::Base
  cache_it :singleton

  def self.singleton
    conds = { :singleton => true }
    cache_it.find(conds) || create(conds)
  end
end

RubyOnRilas_testdusoleil/app/controllers/sysconfigs_controller.rb
class SysconfigsController < ApplicationController
  before_filter :authenticate_user!
  # GET /system
  def show
    @sysconfig = Sysconfig.singleton
    @hit_ips = Hit.select("ip").group("ip").paginate(:page => params[:ip_page], per_page: 30)
    @user_agents = Hit.select("user_agent, ip").group("user_agent").paginate(:page => params[:agent_page], per_page: 30)
  end

  # PUT /system/1
  def update
    @sysconfig = Sysconfig.singleton
    if @sysconfig.update_attributes(params[:sysconfig])
      redirect_to sysconfigs_path, :notice => 'Sysconfig was successfully updated.'
    else
      render :action => "show"
    end
  end

  # POST /system/unban_me
  def unban_me

    blockips = Blockip.where(:ip => request.ip).all
    notice = "#{request.ip} "
    # if not blockips.all? {|b| b.remote?}
    #   notice << "is on a local block list. See admin."
    # elsif blockips.blank?
    
    if blockips.blank?
      notice << "was not found on the block list."
    else
      Blockip.destroy_ips(blockips)
      notice << "was removed from remote block list."
    end
    redirect_to sysconfigs_path, :notice => notice
  end

  # POST /system/reset_cache
  def reset_cache
    Sysconfig.update(Sysconfig.singleton.id, :hit_cache_start => Time.now)
    redirect_to sysconfigs_path, :notice => "The hit cache has been reset."
  end
  
  def sync_data
    sysconfig = Sysconfig.singleton
    dbhandle = sysconfig.connection.raw_connection   # geb raw connection (gets mysql2 client so we can do raw stuff)
    flash[:notice] = ""
    if params[:sync_user_agents]
      sync_user_agents_sql = "INSERT into user_agents (SELECT DISTINCT '' as id, user_agent as user_agent_string, MD5(user_agent) as user_agent_key, now() as created_at, now() as updated_at, campaigns.user_id as user_id  from hits inner join campaigns on hits.campaign_id = campaigns.id) ON DUPLICATE KEY UPDATE updated_at = now(),user_id = campaigns.user_id"
      dbhandle.query(sync_user_agents_sql)
      flash[:notice] += "User Agents were synced and #{dbhandle.affected_rows} records were affected."
    end
    
    if params[:sync_hit_counts]
      sync_hit_counts_sql = "INSERT into hit_counts (SELECT '' as id, count(*) as hits_total, 0 as hits_blocked, hits.campaign_id as campaign_id, user_agents.id as user_agent_id, 0 as blocked, '0000-00-00' as blocked_at, 0 as blocked_by, now() as created_at, now() as updated_at FROM hits JOIN user_agents on MD5(hits.user_agent) = user_agents.user_agent_key GROUP BY hits.campaign_id, user_agents.id) ON DUPLICATE KEY UPDATE updated_at = now()"
      dbhandle.query(sync_hit_counts_sql)
      flash[:notice] += "Hit Counts were synced and #{dbhandle.affected_rows} records were added."
    end
    redirect_to sysconfigs_path
    
  end

  def search_ip
    ips    = params[:search_ip]
    agent = params[:search_agent] 
    @sysconfig = Sysconfig.singleton
    if ips.present?
      ips = ips.gsub(/\t/,'').delete(' ').split(",")
      @hit_ips = Hit.select("ip").where(ip:ips).group("ip").paginate(:page => params[:ip_page], per_page: 30)
    else
      @hit_ips = Hit.select("ip").group("ip").paginate(:page => params[:ip_page], per_page: 30)
    end
    
    if agent.present?
      @user_agents = Hit.select("user_agent, ip").where(user_agent:agent).group("user_agent").paginate(:page => params[:agent_page], per_page: 30)
    else
      @user_agents = Hit.select("user_agent, ip").group("user_agent").paginate(:page => params[:agent_page], per_page: 30)
    end
    render :show
  end

  def add_ban_ip
    Blockip.create(:ip => params[:ban_ip].strip, :source => 'sysconfig')
    notice = "The IP '#{params[:ban_ip].strip}' has been banned."
    # redirect_to sysconfigs_path, :notice => notice    
    render json:{success:{msg:notice, ip:params[:ban_ip].strip}}
  end

  def delete_ban_ip
    blockips = Blockip.where(:ip => params[:unban_ip].strip).all
    Blockip.destroy_ips(blockips)
    notice = "The IP '#{params[:unban_ip].strip}' has been unbanned."    
    # redirect_to sysconfigs_path, :notice => notice
    render json:{success:{msg:notice, ip:params[:unban_ip].strip}}
  end

  def upload_ip_list
    ban_ip = params[:ban_ip]
    file_data = params[:ip_list]
    
    if params[:user][:ban_ip] == '1'
      if ban_ip.present?
        blockips = Blockip.where(:ip => ban_ip.strip).all
        Blockip.destroy_ips(blockips)
        notice = "The IP '#{ban_ip.strip}' has been unbanned."
      end      
      
      if file_data.present?
        file_data = file_data.tempfile
        File.open(file_data, 'r') do |file|
          file.each do |line|
            ip_item = line.split(",")
            blockips = Blockip.where(:ip => ip_item[0].strip).all
            Blockip.destroy_ips(blockips)
          end
        end
        notice = "Ip List uploaded is now unbanned."
      end

    else
      if ban_ip.present?
        Blockip.create(:ip => params[:ban_ip].strip, :source => 'sysconfig')
        notice = "The IP '#{ban_ip.strip}' has been banned."
      end

      if file_data.present?
        file_data = file_data.tempfile
        File.open(file_data, 'r') do |file|
          file.each do |line|
            ip_item = line.split(",")
            Blockip.create(:ip => ip_item[0].strip, :source => 'upload csv file')
          end
        end
        notice = "Ip List uploaded is now banned."
      end      
    end
    
    render json:{success:{msg:notice}}
  end

  def add_ban_agent
    hit = Hit.select("user_agent, ip").where(user_agent:params[:ban_agent]).first
    if hit.present?
      Blockip.create(:ip => hit.ip, :source => 'sysconfig',user_id: hit.campaign.user_id)
      notice = "This useragent '#{params[:ban_agent].strip}' has been banned."
    else
      notice = "Can't find this useragent"
    end
    # redirect_to sysconfigs_path, :notice => notice    
    render json:{success:{msg:notice,agent:params[:ban_agent].strip}}
  end

  def delete_ban_agent
    hit = Hit.select("user_agent, ip").where(user_agent:params[:unban_agent].strip).first
    if hit.present?
      blockips = Blockip.where(:ip => hit.ip).all
      Blockip.destroy_ips(blockips)
      notice = "This useragent '#{params[:unban_agent].strip}' has been unbanned."
    else
      notice = "Can't find this useragent"
    end    
    # redirect_to sysconfigs_path, :notice => notice
    render json:{success:{msg:notice,agent:params[:unban_agent].strip}}
  end


  def upload_agent_list
    ban_agent = params[:ban_agent]
    file_data = params[:agent_list]
    hit = nil
    hit = Hit.select("user_agent, ip").where(user_agent:ban_agent.strip).first if ban_agent.present?

    if params[:user][:ban_agent] == '1'
      
      if hit.present?
        blockips = Blockip.where(:ip => hit.ip).all
        Blockip.destroy_ips(blockips)
        notice = "This useragent '#{ban_agent.strip}' has been unbanned."
      end      
      if file_data.present?
        file_data = file_data.tempfile
        File.open(file_data, 'r') do |file|
          file.each do |line|
            ip_item = line.split(",")
            blockips = Blockip.where(:ip => ip_item[0].strip).all
            Blockip.destroy_ips(blockips)
          end
        end
        notice = "UserAgent List uploaded is now unbanned."
      end

    else
      
      if hit.present?
        Blockip.create(:ip => hit.ip, :source => 'sysconfig',user_id: hit.campaign.user_id)
        notice = "This useragent '#{ban_agent.strip}' has been banned."
      end
      if file_data.present?
        file_data = file_data.tempfile
        File.open(file_data, 'r') do |file|
          file.each do |line|
            ip_item = line.split(",")
            Blockip.create(:ip => ip_item[0].strip, :source => 'upload csv file')
          end
        end
        notice = "UserAgent List uploaded is now banned."
      end

    end
    render json:{success:{msg:notice}}
  end
end

RubyOnRilas_testdusoleil/app/helpers/sysconfigs_helper.rb
module SysconfigsHelper
end

RubyOnRilas_testdusoleil/app/views/sysconfigs/show.html.erb
<div class="page-header">
  <h1>
    System Configuration
    <small>
    </small>
  </h1>
</div>

<%= form_for(@sysconfig, :url => sysconfigs_path) do |f| %>
  <% if @sysconfig.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sysconfig.errors.count, "error") %> prohibited this sysconfig from being saved:</h2>

      <ul>
      <% @sysconfig.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend>Settings</legend>

    <%= f.label :hit_cache_timeout %>
    <%= f.text_field :hit_cache_timeout, :class => :span2 %>

    <%= f.label :admin_password %>
    <%= f.password_field :admin_password %>
  </fieldset>

    <%= f.submit 'save', :class => "btn btn-primary" %>
<% end %>

  <legend>Actions</legend>
    <h3>Unban your current IP: <%= request.ip %></h3>
    <%= button_to 'unban', unban_me_sysconfigs_path, :class => "btn" %>

    <h3>Reset the hit cache</h3>
    <%= button_to 'reset', reset_cache_sysconfigs_path, :class => "btn"  %>
    <hr>
    
    <div class="row">
      <h3 style="margin-left:30px;"> IP and User Agent System Wide Filter</h3>
      <div class="span6">        
        <%= form_for(:ip_list_form, :url => upload_ip_list_sysconfigs_path, remote: true, html:{multipart: true, id:"upload_ip_form"}) do |f| %>
          <div class="span1" style="margin-left: 0px; padding-top: 5px;">
            <div class="checkbox">
              <label for="user_ban_ip">
                <input name="user[ban_ip]" type="hidden" value="0">
                <input id="user_ban_ip" name="user[ban_ip]" type="checkbox" value="1"> UnBann
              </label>
            </div>
          </div>

          <div class="span2" style="margin-left:10px;">
            <%= text_field_tag :ban_ip, nil, placeholder: "Ban IP", class:"span2", style:"" %>
          </div>

          <div class="span2" style="margin-left:20px;">
            <span class="btn btn-default btn-file">
              Browse .CSV or .TXT
              <%= file_field_tag :ip_list %>
            </span>
          </div>
          <%= f.submit 'Submit', :class => "btn btn-default", style:"float:right;", id:"ip_list_submit" %> 
           
        <% end %>
        
        <div class="clearfix"></div>
        
        <%= form_for(:ip_list_form, :url => search_ip_sysconfigs_path, html:{id:"search_ip_form", method: :get}) do |f| %>
          <div class="control-group">
             <div class="controls">
               <div class="input-append">
                <%= text_field_tag :search_ip, params[:search_ip], class:"span5" %>
                <%= submit_tag 'Search IP', :class => "btn btn-default", id:"search_ip_submit" %>
              </div>
             </div>
           </div>
        <% end %>
      
        <div class="clearfix"></div>
        <table class="table table-bordered table-striped table-condensed" id="ban_ip_table">
          <thead>
            <th>No</th>
            <th>IP Address</th>
            <th>Status</th>
          </thead>
          <tbody>
            <% @hit_ips.each_with_index do |ip, index|%>
              <tr>
                <td><%= index+1 %></td>
                <td><%= ip.ip %></td>
                <td><%= Blockip.blocked?(ip.ip) == false ? "UnBanned" : "Banned" %>
              </tr>
            <% end %>
            <tr>
              <td colspan="3">
                <%= will_paginate @hit_ips, param_name: 'ip_page' %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      
      <div class="span6">        
        <%= form_for(:ip_list_form, :url => upload_agent_list_sysconfigs_path, remote: true, html:{multipart: true, id:"agent_upload_form"}) do |f| %>

           <div class="span1" style="margin-left: 0px; padding-top: 5px;">
            <div class="checkbox">
              <label for="user_ban_agent">
                <input name="user[ban_agent]" type="hidden" value="0">
                <input id="user_ban_agent" name="user[ban_agent]" type="checkbox" value="1"> UnBann
              </label>
            </div>
          </div>

          <div class="span3" style="margin-left:10px;">
            <%= text_field_tag :ban_agent, nil, placeholder: "Ban UserAgent", class:"span3", style:"" %>
          </div>

          <div class="span1" style="margin-left:10px;width:146px;">
            <span class="btn btn-default btn-file">
              Browse .CSV or .TXT
              <%= file_field_tag :agent_list %>
            </span>
          </div>
          <%= f.submit 'Submit', :class => "btn btn-default", style:"float:right;", id:"agent_list_submit" %> 


        <% end %>
        
        <div class="clearfix"></div>

        <%= form_for(:ip_list_form, :url => search_ip_sysconfigs_path, html:{id:"search_ip_form", method: :get}) do |f| %>
          <div class="control-group">
             <div class="controls">
               <div class="input-append">
                <%= text_field_tag :search_agent, params[:search_agent], class:"span2", style:"width:430px;" %>
                <%= submit_tag 'Search UserAgent', :class => "btn btn-default", id:"search_useragent_submit" %>
              </div>
             </div>
           </div>
        <% end %>

        <div class="clearfix"></div>


        <table class="table table-bordered table-striped table-condensed" id="ban_agent_table">
          <thead>
            <th>No</th>
            <th>User Agent</th>
            <th>Status</th>
          </thead>
          <tbody>
            <% @user_agents.each_with_index do |ua, index|%>
              <tr>
                <td><%= index+1%></td>
                <td><%= ua.user_agent%></td>
                <td><%= Blockip.blocked?(ua.ip) == false ? "UnBanned" : "Banned" %>
              </tr>
            <% end %>
            <tr>
              <td colspan="3">
                <%= will_paginate @user_agents, param_name: 'agent_page' %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <hr>
    <%= form_for(@sysconfig, :url => sync_data_sysconfigs_path) do |f| %>
      <h3>Sync Data</h3>
       <div class="control-group">
         <div class="controls">
           <label class="checkbox inline"><%= check_box_tag(:sync_user_agents) %> User Agents</label>
           <label class="checkbox inline"><%= check_box_tag(:sync_hit_counts) %> Hit Counts</label>
         </div>
       </div>
       <%= f.submit 'Save', :class => "btn btn-danger" %>
      <p class="help-block">If you sync data, it may take a few minutes and slow the system down.</p>
  <% end %>

<style type="text/css">
  form{
    margin-bottom: 0px;
  }
  .btn-file {
    position: relative;
    overflow: hidden;
  }
  .btn-file input[type=file] {
      position: absolute;
      top: 0;
      right: 0;
      min-width: 100%;
      min-height: 100%;
      font-size: 100px;
      text-align: right;
      filter: alpha(opacity=0);
      opacity: 0;
      outline: none;
      background: white;
      cursor: inherit;
      display: block;
  }
</style>