RubyOnRails_coinfalcon/config/routes.rb
Rails.application.routes.draw do
  devise_for  :users, :path => '', controllers: { registrations: 'registrations' }, skip: [:session]

  as :user do
    get '/login' => 'devise/sessions#new', :as => :new_user_session

    post '/login' => 'devise/sessions#create', :as => :user_session
    
    delete '/logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  namespace :users do
    get 'enable_otp'
    post 'disable_otp'
    post 'sent_enable_otp_email'
    post 'login_without_otp'
  end

  resource :bank_accounts, only: [:create]
  
  # settings
  scope path: 'settings', as: 'settings' do
    get '/' => 'settings#index'
    get '/account' => 'settings#account'
    get '/security' => 'settings#security'

    patch '/account/update' => 'settings#account_update', :as => :account_update
    patch '/security/email_update' => 'settings#email_update', :as => :email_update
    patch '/security/password_update' => 'settings#password_update', :as => :password_update
  end

  get '/transfers' => 'transfers#index'
  scope path: 'transfers', as: 'transfers' do
    scope path: 'deposit', as: 'deposit' do
      get '/euro' => 'deposits#euro'
      get '/bitcoin' => 'deposits#bitcoin'
      get '/new_bitcoin_address' => 'deposits#new_bitcoin_address'
      get '/ethereum' => 'deposits#ethereum'
    end
    scope path: 'withdraw', as: 'withdraw' do
      get '/euro' => 'withdraws#euro'
      post '/euro' => 'withdraws#withdraw_euro', as: :do_euro
      get '/bitcoin' => 'withdraws#bitcoin'
      post '/bitcoin' => 'withdraws#withdraw_bitcoin', as: :do_bitcoin
      get '/ethereum' => 'withdraws#ethereum'
    end
  end

  resource :orders, only: [:new, :create]

  get '/summary' => 'summary#index'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

  match '/404', :to => 'errors#not_found', :via => :all
  match '/500', :to => 'errors#internal_server_error', :via => :all
  mount API::V1::Mount => '/api/v1'
  
  root to: 'landingpage#index'
end

RubyOnRails_coinfalcon/app/models/transfer.rb
# == Schema Information
#
# Table name: transfers
#
#  id            :integer          not null, primary key
#  user_id       :integer
#  amount        :decimal(36, 18)
#  reject_reason :string
#  processed_at  :datetime
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  currency_id   :integer
#  transfer_type :integer
#  address_type  :string
#  address_id    :integer
#  status        :string
#

class Transfer < ApplicationRecord
  belongs_to :bank_account
  belongs_to :currency
  belongs_to :user
  belongs_to :address, :polymorphic => true

  attr_accessor :bitcoin_address

  has_one :bitcoin_network_transaction

  delegate :code, to: :currency, prefix: true
  delegate :email, to: :user, prefix: true
  enum transfer_type: [:deposit, :withdraw]

  scope :withdraw, -> {where(transfer_type: 'withdraw')}
  scope :deposit, -> {where(transfer_type: 'deposit')}


  after_create :update_user_amount

  aasm column: :status do
    state :pending, :initial => true
    state :denied, :completed

    event :deny do
      transitions :from => :pending, :to => :denied
    end

    event :complete do
      transitions :from => :pending, :to => :completed
    end

  end

  def display_status
    if self.address.instance_of?(DepositBitcoinAddress) && !self.completed?
      "Need #{self.bitcoin_network_transaction.rest_confirmations} confirmations"
    else
      self.status
    end
  end

  def address_display_name
    if self.address.instance_of?(WithdrawBitcoinAddress) || self.address.instance_of?(DepositBitcoinAddress)
      self.bitcoin_network_transaction.display_name
    else
      self.address.display_name
    end
  end

  def update_user_amount
    ap 'in update user_amount'
    if self.transfer_type == 'withdraw' && self.pending?
      if self.address.instance_of? WithdrawBitcoinAddress
        ap self
        ap self.address
        self.bitcoin_network_transaction = BitcoinNetworkTransaction.create!(transfer_id: self.id, amount: self.amount)
      end
      currency_sum = "#{currency_code}_sum"
      user.update_attribute( currency_sum, user.send(currency_sum.to_sym) - self.amount)
    elsif self.transfer_type == 'deposit'
    end
  end

end

RubyOnRails_coinfalcon/app/controllers/transfers_controller.rb
class TransfersController < ApplicationController

  def index
    @user = current_user
    render 'transfers/index'
  end
end

RubyOnRails_coinfalcon/app/views/transfers/_histories.slim
- pagination_enable = pagination_enable.nil?? true: pagination_enable
.panel.panel-default
  .panel-heading
    h3 History
  .panel-body.pr-0.pl-0.pb-0.clearfix.dataTables_wrapper
    #histories_container class="#{params[:controller]}_#{params[:action]}"
      = render partial: 'transfers/list', locals: {transfers: transfers}
    - if pagination_enable
      = paginate transfers

RubyOnRails_coinfalcon/app/views/transfers/_links_deposits.slim
.panel-heading
  h3 Currency
.panel-body.d-flex.justify-content-between
  = link_to(transfers_deposit_euro_path)
    .currency-button class=(current_page?(controller: 'deposits', action: 'euro') ? 'active' : '')
      - if current_page?(controller: 'deposits', action: 'euro')
        i.fa.fa-check.checked
      i.icon.euro.mx-auto
      p.mt-2.text-center Euro
  = link_to(transfers_deposit_bitcoin_path)
    .currency-button class=(current_page?(controller: 'deposits', action: 'bitcoin') ? 'active' : '')
      - if current_page?(controller: 'deposits', action: 'bitcoin')
        i.fa.fa-check.checked
      i.icon.bitcoin.mx-auto
      p.mt-2.text-center Bitcoin
  = link_to(transfers_deposit_ethereum_path)
    .currency-button class=(current_page?(controller: 'deposits', action: 'ethereum') ? 'active' : '')
      - if current_page?(controller: 'deposits', action: 'ethereum')
        i.fa.fa-check.checked
      i.icon.ethereum.mx-auto
      p.mt-2.text-center Ethereum

RubyOnRails_coinfalcon/app/views/transfers/_links_withdraws.slim
.panel-heading
  h3 Currency
.panel-body.d-flex.justify-content-between
  = link_to(transfers_withdraw_euro_path)
    .currency-button class="#{active_link_to_class(transfers_withdraw_euro_path, active: [['withdraws'], ['euro', 'withdraw_euro']])}"
      - if current_page?(controller: 'withdraws', action: 'euro')
        i.fa.fa-check.checked
      i.icon.euro.mx-auto
      p.mt-2.text-center Euro
  = link_to(transfers_withdraw_bitcoin_path)
    .currency-button class=(current_page?(controller: 'withdraws', action: 'bitcoin') ? 'active' : '')
      - if current_page?(controller: 'withdraws', action: 'bitcoin')
        i.fa.fa-check.checked
      i.icon.bitcoin.mx-auto
      p.mt-2.text-center Bitcoin
  = link_to(transfers_withdraw_ethereum_path)
    .currency-button class=(current_page?(controller: 'withdraws', action: 'ethereum') ? 'active' : '')
      - if current_page?(controller: 'withdraws', action: 'ethereum')
        i.fa.fa-check.checked
      i.icon.ethereum.mx-auto
      p.mt-2.text-center Ethereum

RubyOnRails_coinfalcon/app/views/transfers/_list.slim
table.table
  thead
    tr
      th
        | Status
      th.text-right
        | Amount
  tbody.no-footer
    - transfers.each do |record|
      tr
        td.v-align-top
          p.fw-500.text-capitalize class=('text-success' if record.completed?) class=('text-danger' if record.denied?)
            = record.display_status
          p = record.created_at.strftime('%Y-%m-%d')
          p = record.address_display_name
        td.v-align-middle.text-right
          - if record.address.instance_of?(DepositBitcoinAddress) || record.address.instance_of?(WithdrawBitcoinAddress)
            h5 = number_to_currency(record.amount, locale: :btc, :precision => (record.amount.round == record.amount) ? 0 : 8)
          - else
            h5 = number_to_currency(record.amount)

RubyOnRails_coinfalcon/app/views/transfers/index.slim
.row
  .col-12.col-sm-12.col-md-8.col-lg-4
    .panel.panel-default.transfers
      ul.nav.nav-tabs.nav-tabs-simple
        li class="#{active_link_to_class(transfers_deposit_euro_path, active: [['deposits'], ['euro', 'bitcoin', 'ethereum']])}"
          = link_to(t('deposit'), controller: 'deposits', action: params[:action])
        li class="#{active_link_to_class(transfers_withdraw_euro_path, active: [['withdraws'], ['euro', 'bitcoin', 'ethereum']])}"
          = link_to(t('withdraw'), controller: 'withdraws', action: params[:action])
      .tab-content
        .tab-pane.active
          .row
            = render 'transfers/links_' + controller_name
            = render 'transfers/' + controller_name + '/' + action_name
  .col-12.col-sm-12.col-md-8.col-lg-4
    - if @transfers.count > 0
      #histories_container
        = render partial: 'transfers/histories', locals: {transfers: @transfers}
    = render 'transfers/' + controller_name + '/infos/' + action_name