RubyOnRilas_testdusoleil/config/routes.rb
Dusoleil::Application.routes.draw do
  #devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)
  # devise_for :admin_users, ActiveAdmin::Devise.config, ActiveAdmin::Devise.config
  devise_for :users

  root :to => "hits#create"

  resources :hits, :only => [:index] do
    post 'ban', :on => :member
    get 'ban', :on => :member
    get 'error_logs', :on => :collection
  end
   get 'check_hit/:id', to: "hits#check_hit"
  resources :campaigns, :except => :edit do
    get 'campaign_clone', :on => :member
    get 'stats', :on => :member
    get 'hits', :on => :member
    get 'hit_counts', :on => :member
    get 'autocomplete', :on => :collection
    get 'referer_autocomplete', :on => :collection
  end
  
  resources :hit_counts, :only => [:index,:put] do
    put 'block', :on => :member
  end

  resources :hit_stats, :only => [:index]
  
  resource :sysconfigs, :only => [:show, :update], :path => "system" do
    post 'unban_me',    :on => :collection
    post 'reset_cache', :on => :collection
    put  'sync_data',   :on => :collection

    get 'search_ip',      :on => :collection
    post 'add_ban_ip',    :on => :collection
    post 'delete_ban_ip', :on => :collection
    post 'upload_ip_list',:on => :collection 

    get 'search_agent',      :on => :collection
    post 'add_ban_agent',    :on => :collection
    post 'delete_ban_agent', :on => :collection
    post 'upload_agent_list',:on => :collection 
  end

  resources :trackers, :except => :edit
end

RubyOnRilas_testdusoleil/app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_filter :get_campaign,        :except => [:new, :create, :index, :autocomplete, :campaign_clone]
  before_filter :get_system_hit_info, :except => [:new, :create, :autocomplete, :campaign_clone]
  before_filter :get_campaign_info,   :except => [:new, :create, :index, :autocomplete, :campaign_clone]
  attr_accessor :browser_time, :ip_time
  before_filter :authenticate_user!

  # GET /campaigns
  def index
    params[:c]  &= Campaign::CREATORS
    params[:t]  &= Tracker.all_domains
    params[:s]  &= ["on","off"]
    params[:tt] &= Campaign::TRAFFIC_TYPE_VALUES
    if current_user.is_admin
      scope = Campaign.where(:archived => false)
    else
      scope = current_user.campaigns.where(:archived => false)
    end


    if params[:key] == params[:key].to_i.to_s
      scope = scope.where(id:params[:key])
    else
      scope = scope.search(params[:key]) if params[:key].present?
      scope = scope.where(:creator => params[:c]) if params[:c].present?
      scope = scope.where(:tracker => params[:t]) if params[:t].present?
      scope = scope.where(:status => params[:s])  if params[:s].present?
      scope = scope.where(:traffic_type => params[:tt]) if params[:tt].present?
    end
    @campaigns = scope.all
    if params[:sort_option] == nil
      @campaigns.sort!{|a,b| b.hit_counts_total <=> a.hit_counts_total}
    elsif params[:sort_option] == 'sorting_asc'
      @campaigns.sort!{|a,b| a.id <=> b.id}
    else
      @campaigns.sort!{|a,b| b.id <=> a.id}
    end
    # @campaigns.sort!{|a,b| b.hit_counts_total <=> a.hit_counts_total}
    @filter_on =  params[:c].present? || params[:t].present? || params[:s].present? || params[:tt].present?
  end

  # GET /campaigns/1
  def show
    ip = request.remote_ip
    if ENV['RAILS_ENV'] == 'development'
       #ip = '103.15.140.69'
       ip = '213.155.18.3'
    end
    @ip_timezone = Campaign.check_timezone(ip)
    @metro_codes_recent, @metro_codes_not_recent = @campaign.all_metro_codes_partition
    @org_other_data = @campaign.filter_organization_other.present? ? @campaign.filter_organization_other.split(",").map{|o| {id:o, name:o.capitalize}} : {}
    @domain_other_data = @campaign.filter_domain_other.present? ? @campaign.filter_domain_other.split(",").map{|o| {id:o, name:o.capitalize}} : {}
  end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
    @campaign.safe_lp = "http://"
    @campaign.real_lp = "http://"
    @campaign.rekey_from_1 = "kw"
    @campaign.rekey_to_1 = "kw"
    @metro_codes_recent, @metro_codes_not_recent = @campaign.all_metro_codes_partition
    ip = request.remote_ip
    if ENV['RAILS_ENV'] == 'development'
       # ip = '103.15.140.69'
      ip = '46.165.220.219'
    end
    @ip_timezone = Campaign.check_timezone(ip)
    render "show"
  end
  
  def campaign_clone
    campaign = Campaign.find(params[:id])
    @new_campaign = campaign.clone
    # @new_campaign.safe_lp = "http://test.com"
    # @new_campaign.real_lp = "http://test.com"
    # @new_campaign.rekey_from_1 = "kw"
    # @new_campaign.rekey_to_1 = "kw"
    @new_campaign.sha1 = ''
    @metro_codes_recent, @metro_codes_not_recent = campaign.all_metro_codes_partition
    if @new_campaign.save
      @campaign = @new_campaign
      redirect_to(@campaign, :notice => 'Campaign was successfully cloned.')
    else
      render :action => "show"
    end
  end

  # POST /campaigns
  def create
    @campaign = current_user.campaigns.new(params[:campaign])
    if ((params[:campaign][:ip_timezone].present?) && params[:campaign][:browser_timezone].present? )
      if(params[:campaign][:ip_timezone].downcase == params[:campaign][:browser_timezone].downcase)
        @campaign.match_timezone = true
      end
    end
    if @campaign.save
      redirect_to(@campaign, :notice => 'Campaign was successfully created.')
    else
      render :action => "show"
    end
  end

  # PUT /campaigns/1
  def update
    # in case it wasn't set at all
    if ((params[:campaign][:ip_timezone].present?) && params[:campaign][:browser_timezone].present? )
      if(params[:campaign][:ip_timezone].downcase == params[:campaign][:browser_timezone].downcase)
        @campaign.update_attributes(match_timezone: true)
      else
        @campaign.update_attributes(match_timezone: false)
      end
    end
    services = params[:campaign][:mail_services]
    params[:campaign][:mail_services] = services.present? ? services.join(",") : ""
    
    params[:campaign][:metro_codes] ||= {}    
    if params[:hidden_email_notification_reset] == 'reset'      
      @campaign.update_attributes(mail_hit:@campaign.hits.count, sent_mail:false)
    end
    status = @campaign.update_attributes(params[:campaign])
    if request.GET.present?  # if coming from index view
      redirect_to campaigns_path
    elsif status
      redirect_to(@campaign, :notice => 'Campaign was successfully updated.')
    else
      @metro_codes_recent, @metro_codes_not_recent = @campaign.all_metro_codes_partition
      render :action => "show"
    end
  end

  # DELETE /campaigns/1
  def destroy
    @campaign.update_attribute(:archived, true)
    redirect_to(campaigns_url)
  end

  # ANY /campaigns/1/stats
  def stats
    @days = (params[:days] || "7").to_i
    today = Date.today
    @stats = (today-@days+1..today).map do |date| 
      stat = Stat.for_date(@campaign.id, date)
    end
    @stats.reverse!
  end
  
  # ANY /campaigns/1/hits
  def hits
    scope = Hit.where(:campaign_id => params[:id])
    scope = scope.order('hits.created_at desc, hits.passed desc').limit(100)
    @hits = scope.all
  end

  # ANY /campaigns/1/hit_counts
  def hit_counts
    @hit_counts = HitCount.includes(:user_agent).where(:campaign_id => params[:id]).order("hits_total DESC").limit(100)
  end
  
  # ANY /campaigns/autocomplete?q=china
  def autocomplete
    q = params[:q].present? ? params[:q].downcase : ''
    results = []
    if q.length >= 3
      results = IplocationdbOrganization.where("LOWER(organization) LIKE ?", "%#{q}%").limit(20)
    end    
    render json: results.map{|r| {id:r.organization.downcase, name:r.organization}}
  end

  def referer_autocomplete
    q = params[:q].present? ? params[:q].downcase : ''
    results = []
    if q.length >= 3
      results = Campaign.where("LOWER(filter_domain_other) LIKE ?", "%#{q}%").limit(20)
    end
    render json: results.map{|r| {id:r.filter_domain_other.downcase, name:r.filter_domain_other.capitalize}}
  end

  protected
  
  def get_campaign
    if current_user.is_admin
      @campaign = Campaign.cache_it.find :id => params[:id].to_i
    else
      @campaign = current_user.campaigns.cache_it.find :id => params[:id].to_i
    end
  end
  
  def get_system_hit_info
    @system_hits_first_at = Hit.first.try(:created_at)
  end
  
  def get_campaign_info
    @campaign_hits_first_at = Hit.where(:campaign_id => params[:id]).first.try(:created_at)
    @campaign_hits_last_at = Hit.where(:campaign_id => params[:id]).last.try(:created_at)
    if @campaign_hits_first_at
      @campaign_days_running = ((@campaign_hits_last_at - @campaign_hits_first_at)/60/60/24).round(1).to_s + " Days"
    end
    @campaign_hits_total = @campaign.present? ? @campaign.hit_counts_total : ''
  end

end

RubyOnRilas_testdusoleil/app/helpers/campaigns_helper.rb
module CampaignsHelper
end

RubyOnRilas_testdusoleil/app/views/campaigns/_header.html.erb
<div class="page-header">
  <h1>
    <%= @campaign.new_record? ? "New Campaign" : "Campaign ##{@campaign.id}"%>
    <% if @campaign.try(:id) %>
      <small>
        Showing hits since: <%= @system_hits_first_at ? raw(label_helper(formatted(@system_hits_first_at),{:type => "info"})) : raw(label_helper('None Recorded Yet',{:type => 'important'}))%>
      </small>
    <% end %>
    <%= link_to "Create Similar Campaign", campaign_clone_campaign_path(@campaign), target: "_blank", class: 'btn btn-default btn-primary' if @campaign.id.present?%>
  </h1>
</div>
<% if @campaign.try(:id) %>
  <div class="row">
    <div class="span12">
      <div class="alert alert-info alert-block">
        <div class="row">
          <div class="span2">
            <p>
              <strong>Creator:</strong> <%= @campaign.creator %><br />
              <strong>Status:</strong> <%= raw(@campaign.formatted_status_flags) %>
            </p>
          </div>
          <div class="span3">
            <p>
              <strong>Tracker:</strong> <%= @campaign.tracker %><br />
              <strong>Traffic Type:</strong> <%= @campaign.traffic_type %>
            </p>
          </div>    
          <div class="span3"> 
            <p>
              <strong>First Hit:</strong> <%= @campaign_hits_first_at ? formatted(@campaign_hits_first_at) : "None" %><br />
              <strong>Last Hit:</strong> <%= @campaign_hits_last_at ? formatted(@campaign_hits_last_at) : "None"  %><br />
            </p>
          </div>
          <div class="span3">
            <p>
              <strong>Running:</strong> <%= @campaign_days_running ? @campaign_days_running : raw("<span class='label label-important'>Not Yet Started</span>") %><br />
              <strong>Total Hits:</strong> <%= @campaign_hits_total %> <span class="">
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

RubyOnRilas_testdusoleil/app/views/campaigns/_tabs.html.erb
<ul class="nav nav-tabs">
  <li class="<%= "active" if request.parameters[:action] === 'show' %>">
    <%= link_to 'Edit', @campaign %>
  </li>
  <li class="<%= "active" if request.parameters[:action] === 'stats' %>">
    <%= link_to 'Daily Stats', stats_campaign_path(@campaign) %>
  </li>
  <li class="<%= "active" if request.parameters[:action] === 'hits' %>">
    <%= link_to 'Latest Hits', hits_campaign_path(@campaign) %>
  </li>
  <li class="<%= "active" if request.parameters[:action] === 'hit_counts' %>">
    <%= link_to 'User Agent Hit Counts', hit_counts_campaign_path(@campaign) %>
  </li>
</ul>

RubyOnRilas_testdusoleil/app/views/campaigns/hit_counts.html.erb
<%= render :partial => "header" %>
<%= render :partial => "tabs" %>

<h2>
  Hit Counts by User Agent
  <small>
    Campaign #<%= @campaign.id%>
  </small>
</h2>

<%= render :partial => "hit_counts/list" %>

RubyOnRilas_testdusoleil/app/views/campaigns/hits.html.erb
<%= render :partial => "header" %>
<%= render :partial => "tabs" %>

<h2>
  Latest Hits
  <small>
    Campaign #<%= @campaign.id %>
  </small>
</h2>
<%= render :partial => "hits/list" %>

RubyOnRilas_testdusoleil/app/views/campaigns/index.html.erb
<style>
  thead .sorting{
    background: url("/img/sort_both.png") no-repeat scroll right center rgba(0, 0, 0, 0)
  }
  thead .sorting_asc{
    background: url("/img/sort_asc.png") no-repeat scroll right center rgba(0, 0, 0, 0)
  }
  thead .sorting_desc{
    background: url("/img/sort_desc.png") no-repeat scroll right center rgba(0, 0, 0, 0)
  }

</style>
<div class="page-header">
  <h1>
    Campaigns
    <small>
      <%= link_to 'New', new_campaign_path, :class => "btn" %>
    </small>
  </h1>
</div>
<div class="span no-margin">
  <div class="alert alert-info alert-small">
    <span class="label label-success">on</span>&nbsp;Campaign&nbsp;is&nbsp;On 
    <span class="label">X</span>&nbsp;Not&nbsp;During&nbsp;Day-Part 
    <span class="label">A(countdown)</span>&nbsp;Autorun&nbsp;Countdown 
    <span class="label">S</span>&nbsp;Started
  </div>
</div>
<div class="span2" style ="margin-left:76px;">
  <%= link_to_function "Show/Hide  Filters", '$("#link-controls").toggleClass("hidden")', :class => "btn" %>
</div>

<div class="span3" style ="margin-left:60px;">
  <%= form_tag campaigns_path, :method => :get, class: "form-search", id: "search_form" do %>
      <div class="input-append">
          <%= text_field_tag :key, params[:key], placeholder: "Search", class: 'input-medium search-query' %>          
          <button type="submit" class="add-on" style="height:28px;"><i class="icon-search"></i></button>
      </div>
      <div>
        <%= hidden_field_tag :sort_option %>
      </div>
  <% end %>
</div>

<% link_controls_class = "hidden" if ! @filter_on %>
<%= content_tag :div, :id => "link-controls", :class => link_controls_class do %>
  <%= form_tag campaigns_path, :method => :get do %>
    <div class="index-control alert alert-info">
      <div class="span3">
        <h3>Creators</h3>
        <%= select_tag :c, options_for_select([["ALL CREATORS",""]]+Campaign::CREATORS, params[:c]), :multiple => true, :size => 8 %>
        <% if params[:c] %>
          <br />
          <% params[:c].each do |c|%>
            <span class="label label-info"><%= c.to_s %></span>
          <% end %>
        <% else %>
          <span></span>
        <% end %>
        <br />
        <br />
        <%= submit_tag "refresh", :name => nil, :class => "btn" %>
      </div>
      <div class="span3">
        <h3>Trackers</h3>
        <%= select_tag :t, options_for_select([["ALL TRACKERS",""]]+Tracker.all_domains, params[:t]), :multiple => true, :size => 8 %>
        <% if params[:t] %>
          <br />
          <% params[:t].each do |t|%>
            <span class="label label-info"><%= t.to_s %></span>
          <% end %>
        <% else %>
          <span></span>
        <% end %>
      </div>
      <div class="span3">
        <h3>Traffic Type</h3>
        <%= select_tag :tt,  options_for_select([["ALL TRAFFIC TYPES",""]]+Campaign::TRAFFIC_TYPE_VALUES, params[:tt]), :multiple => true, :size => 8 %>
        <% if params[:tt].present? %>
          <br />
          <% params[:tt].each do |tt|%>
            <span class="label label-info"><%= tt.to_s %></span>
          <% end %>
        <% else %>
          <span></span>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>
<table class="table table-bordered table-striped table-condensed" id="campaign_list">
  <thead>
    <th style="width: 35px;" >Serial</th>
    <th style="width:35px;text-align:center;cursor:pointer;" class="<%= params[:sort_option].present? ? params[:sort_option] : 'sorting'%>">ID</th>
    <th style="width:90px">Actions</th>
    <th style="width:60px">Status</th>
    <th style="width:200px">Latest</th>
    <th style="width:40px">Hits</th>
    <th style="width:80px"><%= Campaign.human_attribute_name(:creator) %></th>
    <th style="width:90px"><%= Campaign.human_attribute_name(:tracker) %></th>
    <th style="width:100px"><nobr>Traffic Type</nobr></th>
    <th>Landing Page URLs <span class="label label-help" rel="popover" data-original-title="Key" data-content="<span class='label'>R</span> Real Landing Page<br /><span class='label'>S</span> Safe Landing Page" data-html="true">?</span></th>
  </thead>
  <tbody>
  <% @campaigns.each_with_index do |campaign,i| %>
    <tr>
      <td><%=  i + 1  %></td>
      <td style="text-align:center; vertical-align:middle;">
        <% #raw('%3d' % campaign.id).gsub(/[\s]/,'&nbsp;') %>        
        <span class="label label-important" rel="popover" style="background-color:transparent;color:black;font-size:14px;font-weight:400;" data-original-title="Campaign Info!" data-content="Campaign ID: <%= campaign.id %>
          <hr />
          Description: <%= campaign.description %>
          <br />
          ">
        <%= campaign.id %>
        </span>
      </td>
      <td style="vertical-align:middle;">
        <nobr>
        <%= link_to 'Edit', campaign, :class => "btn btn-tiny" %>
        <%= link_to 'Stats', stats_campaign_path(campaign), :class => "btn btn-tiny" %>
        </nobr>
      </td>
      <td style="vertical-align:middle;">
        <% if campaign.status == "on" %>
          <%= link_to 'On', campaign_path(campaign, :campaign => {:status => "on"}), :method => :put, :class => "btn btn-tiny btn-success", "data-rel" => "tooltip", "data-original-title" => "Turn Off?" %>
        <% else %>
        <%= link_to 'Off', campaign_path(campaign, :campaign => {:status => "off"}), :method => :put, :class => "btn btn-tiny", "data-rel" => "tooltip", "data-original-title" => "Turn On?" %>
        <% end %>
        <br />
        <nobr> 
          <%= raw(campaign.formatted_status_flags) %>
        </nobr>
      </td>
      <td style="vertical-align:middle;"><nobr><%= campaign.hits.last ? formatted(campaign.hits.last.created_at) : "None" %></nobr></td>
      <td style="vertical-align:middle;"><%= link_to "#{campaign.hit_counts_total}", hits_campaign_path(campaign) %></td>      
      <td style="vertical-align:middle;"><%= campaign.creator %></td>
      <td style="vertical-align:middle;"><%= campaign.tracker %></td>
      <td style="vertical-align:middle;"><%= campaign.traffic_type %></td>
      <td>
        <span class="label">R</span> <%= campaign.real_lp.truncate(60) %><br />
        <span class="label">S</span> <%= campaign.safe_lp.truncate(60) %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
Showing hits since: <%= @system_hits_first_at ? raw(label_helper(formatted(@system_hits_first_at),{:type => "info"})) : raw(label_helper("None Recorded Yet",{:type => "important"})) %>

RubyOnRilas_testdusoleil/app/views/campaigns/stats.html.erb
<%= render :partial => "header" %>
<%= render :partial => "tabs" %>

<h2>
  Daily Stats
  <small>
  </small>
</h2>
<br />
<%= content_tag :form, :action => stats_campaign_path(@campaign), :method => "get" do %>
  Days: <%= text_field_tag :days, @days, :size => 10 %>
  <%= submit_tag 'view', :name => nil %>
<% end %>
<p/>
<table class="table table-bordered table-striped table-condensed">
  <thead>
    <tr>
      <th>Date</th>
      <th>Hits</th>
      <th>Analyzed</th>
      <th>Passed</th>
      <th>Rejected</th>
      <th>IP</th>
      <th style="width: 100px;">ISP/Organization</th>
      <th>Referrer</th>
      <th>TimeZone</th>
      <th>Proxy IP</th>
      <th>Mobile</th>
      <th style="width: 76px;">Wifi/Carrier</th>
      <th style="width: 76px;">Browser</th>
      <th>Domain</th>
      <th>Geo</th>
    </tr>
  </thead>
  <tbody>
<% @stats.each do |stat| %>
  <tr>
    <td><%= formatted(stat.run_at) %></td>
    <td><%= stat.hits %></td>
    <td><%= stat.analyzed %></td>
    <td><%= stat.analyzed == 0 ? "n/a" : number_to_percentage(stat.passed_pct, :precision => 1) %></td>
    <td><%= stat.analyzed == 0 ? "n/a" : number_to_percentage(stat.rejected_pct, :precision => 2) %></td>
    <td><%= stat.analyzed == 0 ? "n/a" : number_to_percentage(stat.blocked_ip_pct, :precision => 2) %></td>
    <td><%= stat.analyzed == 0 ? "n/a" : number_to_percentage(stat.blocked_isp_organization_pct, :precision => 2) %></td>    
    <td><%= stat.analyzed == 0 ? "n/a" : number_to_percentage(stat.blocked_referrer_pct, :precision => 2) %></td>
    <td><%= stat.analyzed == 0 ? "n/a" : number_to_percentage(stat.blocked_time_zone, :precision => 2) %></td>
    <td><%= stat.analyzed == 0 ? "n/a" : number_to_percentage(stat.blocked_proxy_ip_pct, :precision => 2) %></td>
    <td><%= stat.analyzed == 0 ? "n/a" : number_to_percentage(stat.blocked_mobile_pct, :precision => 2) %></td>
    <td><%= stat.analyzed == 0 ? "n/a" : number_to_percentage(stat.blocked_wifi_carrier_pct, :precision => 2) %></td>
    <td><%= stat.analyzed == 0 ? "n/a" : number_to_percentage(stat.blocked_browser_pct, :precision => 2) %></td>
    <td><%= stat.analyzed == 0 ? "n/a" : number_to_percentage(stat.blocked_domain_pct, :precision => 2) %></td>
    <td><%= stat.analyzed == 0 ? "n/a" : number_to_percentage(stat.blocked_geocode_pct, :precision => 2) %></td>
  </tr>
<% end %>
  </tbody>
</table>